unit Qollector.Migrations;

interface

uses
  System.SysUtils, System.Generics.Collections,
  Spring, Spring.Collections, Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('MIGRATIONS')]
  TMigration = class
  private
    [Column('ID', [cpRequired, cpPrimaryKey])][AutoGenerated]
    FId: Integer;
    FMigration: Integer;
    FStatus: Integer;
  public
    constructor Create; virtual;
    property Id: Integer read FId;

    [Column('MIGRATION')]
    property Migration: Integer read FMigration write FMigration;

    [Column('STATUS')]
    property Status: Integer read FStatus write FStatus;
  end;

implementation

{ TMigration }

constructor TMigration.Create;
begin
  inherited Create;
end;

end.
